version: '2'

services:
  nginx:
    container_name: sikr_nginx
    image: nginx:mainline-alpine
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=443
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  api:
    container_name: sikr_api
    image: sikr/api:latest
    volumes:
      - ./api:/srv/sikr-
    ports:
      - "8080"
    depends_on:
      - database

  database:
    container_name: sikr_postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=sikr
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=sikr_vault
    volumes:
      - /srv/db:/var/lib/postgres
    ports:
      - "5432"
